scene.setBackgroundColor(10)
let mySprite = sprites.create(assets.image`AJ`, SpriteKind.Player)
controller.moveSprite(mySprite)
scene.setBackgroundImage(assets.image`sunny`)
mySprite.sayText("I'M My'Angel", 2000, true)
pause(2000)
mySprite.sayText("I'm in the 11th grade", 2000, true)
pause(2000)
mySprite.sayText("I like to play volleyball", 2000, true)
pause(2000)
